"""empty message

Revision ID: 53ff1440079c
Revises: 2b4b1b78d691
Create Date: 2025-03-05 02:34:25.139476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53ff1440079c'
down_revision = '2b4b1b78d691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('final_standings', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contest', schema=None) as batch_op:
        batch_op.drop_column('final_standings')

    # ### end Alembic commands ###
